name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
 Je   steps:
    - uses: actions/checkout@v3
    - name: make clean
      run: make clean
    - name: make test
      run: make test
